baseURL = "https://ooni.torproject.org"
languageCode = "en-us"
title = "OONI: Open Observatory of Network Interference"
DefaultContentLanguage = "en"
pluralizeListTitles = false

[Languages]
[Languages.en]
[Languages.es]
[Languages.ca]
[Languages.fr]
[Languages.pt]
[Languages.zh]

[outputFormats]
[outputFormats.PageIndex]
mediaType = "application/json"
baseName = "pageindex"
isPlainText = true
notAlternative = true

[outputs]
  home = ["HTML", "PageIndex", "RSS"]
